### ISSUE TITLE
Loaded from local storage toast appears for deleted entries.

### ISSUE THREAD

**Issue by cdubz** [overshard/timelite#18]
Whenever I reload the app after deleting some entries, I still see toasts for those entries --

![image](https://user-images.githubusercontent.com/10456740/61471600-ddbda700-a937-11e9-9cbe-899cac3c9479.png)

**Comment by overshard** [comment]
It's still loading up localStorage, just an empty string, I agree it's kind of confusing. It will be less confusing the latest PR I'm crafting #19 since it's just a single info toast saying "local storage has been loaded". and not 2-3 based on every item.

**Comment by overshard** [comment]
This is improved in the latest release
