### ISSUE TITLE
Prevent numbers jumping around

### ISSUE THREAD

**Issue by JeroenBakker** [overshard/timelite#32]
First off, love the simplicity of the app, nice work!

So, because different numbers have different sizes and the text is aligned to the center the whole time keeps jumping from left to right whenever the width of the time changes.

I believe this would be easily fixed by applying `font-variant-numeric: tabular-nums;` to the time.

**Comment by insulatir** [comment]
I can make PR for this.

**Comment by overshard** [comment]
This has been fixed by @insulatir and merged.
