### ISSUE TITLE
Add keyboard shortcuts for all common actions

### ISSUE THREAD

**Issue by overshard** [overshard/timelite#37]
- Reset timer
- Add timer
- Swap to log
- Swap to timer
- Tabbing through log
- Edit log entry
- Save log entry
- Clear log

**Comment by domind** [comment]
@overshard would like to do this one. Can I?

**Comment by overshard** [comment]
@domind feel free to do a PR! I haven't got to this yet and it's be super nice to have.

**Comment by domind** [comment]
@overshard Sent [PR](https://github.com/overshard/timelite/pull/39) 

Added following shortcuts:
- Reset timer - alt+r
- Add timer - alt+a
- Swap to log - alt+l
- Swap to timer - alt+m (alt+t is browser shortcut for tools)
- Swap to about page - alt+o
- Clear log - alt+c

Let me know if OK, then next week will try to work on this log shortcuts:

- [ ] Tabbing through log
- [ ] Edit log entry
- [ ] Save log entry
- [ ] bringing focus to "add note" input?

**Comment by domind** [comment]
Had closer look into this log editing shortcuts. Right now if you have focus in log entries you can tab:
edit->delete ->next entry edit -> next entry delete, and so on.  On selected items hitting enter will activate it. Arrows will scroll list up and down. Only problem is that this focus highlight is barely visible.
To fix this we would need to mark somehow active entry and keep somewhere state which one is selected. Better to keep "selected" as property in log entry, or just to keep in state id of selected one? 
Each solution will require other handling when entry is removed

**Comment by overshard** [comment]
Went ahead and merged the current PR, clean and works. We do need to decide on a way to showcase shortcuts somehow/help users discover them and then all the log editing stuff.

**Comment by domind** [comment]
Added highlighting of entries in log. Will work further on this.

**Comment by domind** [comment]
@overshard seems that managed to add all shortcuts. There are some glitches that I have problems to eliminate.
1. when changing to log with keyboard - you need to click on list to be able to move highlighter
2. after editing log entry - state update is not passed immediately to hot-keys component(but only here), so for some time moving with arrows to other entry does not work. 
Still even with those issues, this looks quite OK. Might be next week will try to eliminate it, but not sure. If you got any hints how - will appreciate if you let me know.

**Comment by overshard** [comment]
Thanks to @domind 's amazing work this seems to be all done! Everything works very smoothly on my end. I really appreciate the contribution.
