### ISSUE TITLE
Add new stats page w/ charts

### ISSUE THREAD

**Issue by overshard** [overshard/timelite#5]

**Comment by overshard** [comment]
Having thought about this a bit, this isn't all that useful without daily storage being added so working on that first.

**Comment by kanodiaayush** [comment]
Will be useful to get summary information about which tags I spent my most time on and such.

**Comment by overshard** [comment]
@kanodiaayush in the latest push I've added a new summary page w/ a graph for tags and time spent, let me know if that's what you're looking for and if you have any further suggestions here!
